version: '3.8'

services:
  app:
    build: .
    container_name: book-reminder-container
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: 'book_123'
      DATABASE_NAME: book_reminder
    volumes:
      - .:/app
    command: ["rails", "server", "-b", "0.0.0.0"]

  db:
    image: mariadb:latest
    container_name: book-reminder-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'db_123'
      MYSQL_DATABASE: book_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
